create database CROSSOVER
USE CROSSOVER;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE KEY,
  password_hash VARCHAR(255) NOT NULL
);